name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"

jobs:

  build-and-test:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - uses: actions/checkout@v2

      - name: setup .NET
        uses: actions/setup-dotnet@v2
        
      - name: restore dependencies
        run: dotnet restore src/Instruments.sln

      - name: run tests
        env:
          FBN_TOKEN_URL: ${{ secrets.MASTER_FBN_TOKEN_URL }}
          FBN_USERNAME: ${{ secrets.MASTER_FBN_USERNAME }}
          FBN_PASSWORD: ${{ secrets.MASTER_FBN_PASSWORD }}
          FBN_CLIENT_ID: ${{ secrets.MASTER_FBN_CLIENT_ID }}
          FBN_CLIENT_SECRET: ${{ secrets.MASTER_FBN_CLIENT_SECRET }}
          FBN_LUSID_API_URL: ${{ secrets.MASTER_FBN_LUSID_API_URL }}
          FBN_APP_NAME: ${{ secrets.MASTER_FBN_CLIENT_ID }}
          FBN_LUSID_ACCESS_TOKEN: ${{ secrets.MASTER_FBN_ACCESS_TOKEN }}
        run: dotnet test src/Instruments.sln -l "console;verbosity=detailed"